### PR TITLE
Refactor ItemRepo unit tests #345

### LINKED ISSUE #345: Refactor items repo unit tests
As part of #90 following on from #342.

### PR DESCRIPTION
**Pull request by joelvdavies**
## Description
See #345.

### Notes
- I noticed we test the `system_id` existence in the create, but not in the update (we do that in the service layer) - we may want to change this later for consistency
- Removed `test_list_with_invalid_system_id_filter` none of the other repo tests do invalid id checks
- Removed `test_with_catalogue_item_id_filter_no_matching_results` and `test_list_with_system_id_filter_no_matching_results` and similar - they are instead tested at once in `test_list_with_system_id_and_catalogue_category_id_with_no_results`

## Testing instructions
Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage

## Agile board tracking
Closes #345

### CODE REVIEW

**Comment by VKTB** [comment]
> - I noticed we test the `system_id` existence in the create, but not in the update (we do that in the service layer) - we may want to change this later for consistency

Sorry but what are you suggesting we change for consistency? The reason we are asserting in the service unit tests for update is because the `system_id` existence check lives in the service layer. Are you suggesting that we keep the existence checks in one same layer?

**Review by VKTB — APPROVED** [review]
LGTM

**Comment by joelvdavies** [comment]
> > * I noticed we test the `system_id` existence in the create, but not in the update (we do that in the service layer) - we may want to change this later for consistency
> 
> Sorry but what are you suggesting we change for consistency? The reason we are asserting in the service unit tests instead of the repo unit tests for update is because the `system_id` existence check lives in the service layer. Are you suggesting that we keep the existence checks in one same layer?

Yeah I think that's what I meant - again I think I was just voicing a thought as I went through them that we haven't been consistent.

**Comment by VKTB** [comment]
> > > * I noticed we test the `system_id` existence in the create, but not in the update (we do that in the service layer) - we may want to change this later for consistency
> > 
> > 
> > Sorry but what are you suggesting we change for consistency? The reason we are asserting in the service unit tests instead of the repo unit tests for update is because the `system_id` existence check lives in the service layer. Are you suggesting that we keep the existence checks in one same layer?
> 
> Yeah I think that's what I meant - again I think I was just voicing a thought as I went through them that we haven't been consistent.

I think for some checks there are reasons why they are not in the same layer but for this one it seems like (at first glance) that it can be moved to one layer.

**Pull request merged**
